# Configure main menu and social menu

# [[main]]
#     identifier = "home"
#     name = "Home"
#     url = "https://github.com/AminiamEva"

#     [main.params]
#         icon = "home"
#         newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/AminiamEva"

    [social.params]
        icon = "brand-github"

# [[social]]
#     identifier = "twitter"
#     name       = "Twitter"
#     url        = "https://twitter.com"

#     [social.params]
#         icon = "brand-twitter"

[[social]]
    identifier = "zhihu"
    name       = "知乎"
    url        = "https://www.zhihu.com/people/Aminiam"

    [social.params]
        icon = "brand-zhihu"
